name: update_docs

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1

    - name: Install asciidoctor package
      run:  sudo apt-get update && sudo apt-get upgrade -y asciidoctor

    - name: Build Docs
      run:  asciidoctor -D docs --backend=html5 index.adoc  -o index.html

    - name: Deploy docs to ghpages
      uses: peaceiris/actions-gh-pages@v3
      env:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./
