name: update_docs

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    name: asciidoc builder
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build AsciiDoc step
      id: adocbuild
      uses: avattathil/asciidoctor-action@master
      with:
        program: "asciidoctor -D docs --backend=html5 index.adoc  -o index.html" 
    - name: Print execution time
      run: echo "Time ${{ steps.adocbuild.outputs.time }}"
    - name: Deploy docs to ghpages
      uses: peaceiris/actions-gh-pages@v3
      env:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./
