name: update_docs

on:
  push:
    branches:
    - master
jobs:
  build-adocs:
    runs-on: ubuntu-18.04
    name: asciidoc builder
    steps:
    - name: Checkout master
      uses: actions/checkout@v2
    - name: Get build container
      id: adoc
      uses: avattathil/asciidoctor-action@master
      with:
          program: "asciidoctor -D docs --backend=html5 -o index.html -a toc2 docs/index.adoc"
    - name: upload assets
      uses: actions/upload-artifact@v1
      with:
        name: adoc
    - name: Print execution time
      run: echo "Time ${{ steps.adoc.outputs.time }}"
    - name: Checkout gh-pages
      uses: actions/checkout@v1
      with:
        refs: gh-pages
    - uses: actions/download-artifact@v1
      with:
        name: adoc
        path: .
    - name: Push updates
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "Update docs" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
    - name: Print execution time
      run: echo "Time ${{ steps.adoc.outputs.time }}"
