name: update_docs

on:
  push:
    branches:
    - master
jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    name: asciidoc builder
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Get build container
      id: adocbuild
      uses: avattathil/asciidoctor-action@master
      with:
          program: "_ADOCS=$(mktemp -d) && asciidoctor -D ${_ADOCS} --backend=html5 -o index.html -a toc2 docs/index.adoc"
    - name: Push to ghpages branch
      run: |
          git config --global avattathil 'Tony Vattathil'
          git config --global user.email 'avattathil@gmail.com'
          git checkout gh-pages
          mv ${_ADOCS}/* .
          git add -A
          git commit -a -m 'Update Docs'
          git push
    - name: Print execution time
      run: echo "Time ${{ steps.adocbuild.outputs.time }}"
