name: update_docs

on:
  push:
    branches:
    - master
jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    name: asciidoc builder
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Get build container
      id: adocbuild
      uses: avattathil/asciidoctor-action@master
      with:
          program: "asciidoctor -D ${_ADOCS} --backend=html5 -o index.html -a toc2 docs/index.adoc"
    - name: upload assets
      uses: actions/upload-artifact@v1
      with:
        name: adocbuild
        path: ./
    - name: Print execution time
      run: echo "Time ${{ steps.adocbuild.outputs.time }}"
